export const PackageActionTypes = {
  SET_PACKAGES_START: "SET_PACKAGES_START",
  SET_PACKAGES_SUCCESS: "SET_PACKAGES_SUCCESS",
  SET_PACKAGES_FAILURE: "SET_PACKAGES_FAILURE",
  SET_SELECTED_PACKAGE: "SET_SELECTED_PACKAGE",
};
