export const ManagementActionTypes = {
  FETCH_MANAGEMENT_START: "FETCH_MANAGEMENT_START",
  FETCH_MANAGEMENT_SUCCESS: "FETCH_MANAGEMENT_SUCCESS",
  FETCH_MANAGEMENT_FAILURE: "FETCH_MANAGEMENT_FAILURE",
  SET_MANAGEMENT_TOKENS: "SET_MANAGEMENT_TOKENS",
};
