export const UserActionTypes = {
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  FETCH_REG_TOKEN_START: "FETCH_REG_TOKEN_START",
  FETCH_REG_TOKEN_SUCCESS: "FETCH_REG_TOKEN_SUCCESS",
  FETCH_REG_TOKEN_FAILURE: "FETCH_REG_TOKEN_FAILURE",
};
