export const TeacherActionTypes = {
    FETCH_COURSES_START: 'FETCH_COURSES_START',
    FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
    FETCH_COURSES_FAILURE: 'FETCH_COURSES_FAILURE',
    CLEAR_COURSES_ON_SIGNOUT: 'CLEAR_COURSES_ON_SIGNOUT',
    FETCH_STUDENTS_LIST_OF_COURSE_START: 'FETCH_STUDENTS_LIST_OF_COURSE_START',
    FETCH_STUDENTS_LIST_OF_COURSE_SUCCESS: 'FETCH_STUDENTS_LIST_OF_COURSE_SUCCESS',
    FETCH_STUDENTS_LIST_OF_COURSE_FAILURE: 'FETCH_STUDENTS_LIST_OF_COURSE_FAILURE'
};